version: '3'
services: 
  shop:
    build: ../Shop
    ports:
    - "5001:5001"
    environment:
      ASPNETCORE_URLS: "http://+:5001"
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
    - './:/app'