version: '3'
services: 
  shop:
    build: ./
    ports:
    - "5001:5001"
    environment:
      ASPNETCORE_URLS: "http://+:5001"
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
    - './:/app'
    depends_on:
    - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    hostname: sql-server
    container_name: sql-server
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=123(!)Password
      # - MSSQL_PID=Express
    volumes:
      - ~/mssql-server-data:/var/opt/mssql/data